version: "2"
services: 
  api:
    image: api
    build: 
      context: ./api
    ports: 
      - "3000:3000"
    command: npm start mongo
  mongo:
    image: mongo:3.6.2-jessie
    ports: 
      - "27017:27017"