POST http://localhost:3000/pongs HTTP/1.1
Content-Type: application/json

{
    "first_name": "james",
    "family_name": "pong"
}

###
GET http://localhost:3000/pongs HTTP/1.1
###
GET http://localhost:3000/ping HTTP/1.1